name: Terraform Validate

on:
  pull_request:
    paths:
      - "terraform/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform fmt -check -recursive terraform/
      - name: Terraform validate (dev)
        run: cd terraform/environments/dev && terraform init -backend=false && terraform validate
      - name: Terraform validate (staging)
        run: cd terraform/environments/staging && terraform init -backend=false && terraform validate
      - name: Terraform validate (production)
        run: cd terraform/environments/production && terraform init -backend=false && terraform validate
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
      - name: TFLint
        run: tflint --chdir=terraform
      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
